CREATE TABLE IF NOT EXISTS addrobj
(
    aoid            TEXT    NOT NULL PRIMARY KEY,
    aoguid          TEXT    NOT NULL,
    parentguid      TEXT,
    formalname      TEXT,
    offname         TEXT,
    shortname       TEXT,
    aolevel         TEXT,
    regioncode      TEXT,
    areacode        TEXT,
    autocode        TEXT,
    citycode        TEXT,
    ctarcode        TEXT,
    placecode       TEXT,
    plancode        TEXT,
    streetcode      TEXT,
    extrcode        TEXT,
    sextcode        TEXT,
    plaincode       TEXT,
    code            TEXT,
    currstatus      TEXT,
    actstatus       TEXT,
    livestatus      TEXT,
    centstatus      TEXT,
    operstatus      TEXT,
    ifnsfl          TEXT,
    ifnsul          TEXT,
    okato           TEXT,
    oktmo           TEXT,
    startdate       TEXT,
    enddate         TEXT,
    updatedate      TEXT,
    normdoc         TEXT,
    divtype         TEXT,
    nextid          TEXT,
    terrifnsfl      TEXT,
    terrifnsul      TEXT,
    postalcode      TEXT,
    previd          TEXT
    );

COMMENT ON TABLE addrobj IS 'addrobj';
